apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  labels:
    app: tomcat9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat9
  template:
    metadata:
      labels:
        app: tomcat9
    spec:
      containers:
      - name: tomcat
        image: docker.repo1.uhc.com/mukul-test/tomcat:8.0
        ports:
        - containerPort: 8080
